---

- hosts: all
  become: true
  tasks:


  - name: install apache2 package
    apt:
      name: 
        - apache2
        - libapache2-mode-php
      state: latest
      update_cache: yes
    #when: ansible_distribution == "Ubuntu"
    when: ansible_distribution in ["Kali"]

  - name: install apache2 package
    yum:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    #when: ansible_distribution == "CentOS"
   #when: ansible_distribution in ["Debian", "Ubuntu"] 
    when: ansible_distribution in ["Redhat", "Centos"]
